#!/bin/sh

if [ -z "$1" ]; then
    echo "Usage: $(basename $0) <vmname>"
    exit 1
fi

if [ ! -f vm"$1".qcow2 ]; then
    echo "No such VM"
    exit 1
fi

qemu-system-x86_64 \
    -machine type=q35,accel=kvm \
    -nographic \
    -smp 2 \
    -m 2G \
    -drive if=virtio,file=vm${1}.qcow2,format=qcow2,media=disk \
    -netdev user,id=internet,ipv4=on,ipv6=off \
    -device virtio-net,netdev=internet
