#!/bin/sh

[ "$(uname)" = Linux ] && SECCOMP=on || SECCOMP=off

if [ -z "$1" ]; then
    echo "Usage: $(basename $0) <vmname>"
    exit 1
fi

if [ ! -f vm"$1".qcow2 ]; then
    echo "No such VM"
    exit 1
fi

qemu-system-x86_64 \
    -sandbox "${SECCOMP}" \
    -machine type=q35,accel=kvm:hvf \
    -nographic \
    -smp 2 \
    -m 2G \
    -drive if=virtio,file=vm${1}.qcow2,format=qcow2,media=disk \
    -nic user,ipv6=off,model=virtio
