#!/usr/bin/expect -f

# Make sure we have installmedia and clean root disk
exec curl -sOC- https://cdn.openbsd.org/pub/OpenBSD/6.7/amd64/install67.iso
exec qemu-img create -f qcow2 vmuno.qcow2 20G

spawn qemu-system-x86_64 \
    -no-reboot \
    -machine type=q35,accel=kvm \
    -nographic \
    -smp 2 \
    -m 2G \
    -drive if=virtio,file=vmuno.qcow2,format=qcow2,media=disk \
    -drive file=install67.iso,media=cdrom \
    -netdev user,id=internet,ipv4=on,ipv6=off \
    -device virtio-net,netdev=internet

# Catch bootloader to set console to serial, and continue boot
expect "boot>"
send "set tty com0\r"
expect "boot>"
send "boot\r"

# Wait to be presented by options, and drop to shell
expect "\(S\)hell?"
send "s\r"

# Write autoinstall answers
expect "#"
send "cat << EOF > /auto_install.conf\r"

expect ">"
send [exec cat vmuno-install.conf]
send "\rEOF\r"

# Exit shell and trigger autoinstall directly instead of waiting for timeout
expect "#"
send "exit\r"

expect "\(S)hell?"
send "a\r"

# Wait for autoinstalll to finish"
expect "rebooting..."

# Catch all
interact
